Name:           perl-DBIx-Simple
Version:        1.32
Release:        3%{?dist}
Summary:        Easy-to-use OO interface to DBI
License:        Public Domain
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/DBIx-Simple/
Source0:        http://www.cpan.org/authors/id/J/JU/JUERD/DBIx-Simple-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(DBI) >= 1.21
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::Simple)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
DBIx::Simple provides a simplified interface to DBI, Perl's powerful
database module.

%prep
%setup -q -n DBIx-Simple-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install DESTDIR=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Feb 18 2010 Marcela Mašláňová <mmaslano@redhat.com> 1.32-3
- rebuild for CPANPLUS
- Related: rhbz#543948

* Fri Jan 15 2010 Stepan Kasal <skasal@redhat.com> - 1.32-2
- rebuild against perl 5.10.1

* Wed Aug 12 2009 Marcela Mašláňová <mmaslano@redhat.com> 1.32-1
- Specfile autogenerated by cpanspec 1.78.
